config/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pages.urls')),
    path('products/', include('products.urls')),
    path('ckeditor/', include('ckeditor_uploader.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pages/urls.py
from django.urls import path
from django.shortcuts import render, redirect

from . import views

app_name = 'pages'
urlpatterns = [
    path('', views.index, name='index'),
    path('contact', views.contact, name='contact'),
]

products/urls.py
from django.urls import path

from . import views

app_name = 'products'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:pk>', views.detail, name='detail'),
    path('category/<str:pk>', views.category, name='category'),
]

pages/models.py
from django.db import models

# Create your models here.

products/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField


class Category(models.Model):
    category_text = models.CharField(max_length=128)

    def __str__(self):
        return self.category_text


class Brand(models.Model):
    brand_text = models.CharField(max_length=128)

    def __str__(self):
        return self.brand_text


class Product(models.Model):
    product_text = models.CharField(max_length=128)
    measurable_range = models.CharField(max_length=128)
    option = models.CharField(max_length=128)
    serial_number = models.CharField(max_length=32)
    rank = models.CharField(max_length=8)
    year_of_manufacture = models.CharField(max_length=8)

    price = models.IntegerField()

    description = RichTextUploadingField()

    IN_STOCK = 'In Stock'
    SOLD = 'Sold'
    NEED_TO_CONFIRM = 'Need To Confirm'
    INVENTORY_STATUS = (
        (IN_STOCK, IN_STOCK),
        (SOLD, SOLD),
        (NEED_TO_CONFIRM, NEED_TO_CONFIRM),
    )

    inventory_status = models.CharField(
        max_length=128,
        choices=INVENTORY_STATUS,
        default=IN_STOCK,
    )

    brand = models.ForeignKey(Brand, on_delete=models.CASCADE)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)

    def __str__(self):
        return (self.product_text) + ":" + str(self.id)

    def __unicode__(self):
        return u"{}".format(self.your_field)


class Image(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='images/')
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

pages/forms.py
from django import forms

class ContactForm(forms.Form):
    company = forms.CharField(required=True,
                              widget=forms.TextInput(attrs={'class': 'form-control',
                                                            'placeholder': '会社名'}))

    division = forms.CharField(required=True,
                               widget=forms.TextInput(attrs={'class': 'form-control',
                                                             'placeholder': '部署名'}))

    name = forms.CharField(required=True,
                           widget=forms.TextInput(attrs={'class': 'form-control',
                                                         'placeholder': '氏名'}))

    address = forms.CharField(required=True,
                              widget=forms.TextInput(attrs={'class': 'form-control',
                                                            'placeholder': '住所'}))

    phone_number = forms.CharField(required=True,
                                   widget=forms.TextInput(attrs={'class': 'form-control',
                                                                 'placeholder': '電話番号'}))

    email = forms.EmailField(required=True,
                             widget=forms.TextInput(attrs={'class': 'form-control',
                                                           'placeholder': 'メールアドレス'}))

    content = forms.CharField(
        required=True,
        widget=forms.Textarea(attrs={'class': 'form-control',
                                     'placeholder': 'お問合せ内容'})
    )

pages/views.py
from django.shortcuts import render, redirect

def index(request):
    return render(request, 'pages/index.html')

def contact(request):
    from .forms import ContactForm
    from django.core.mail import EmailMessage
    from django.template import Context
    from django.template.loader import render_to_string

    form_class = ContactForm

    # new logic!
    if request.method == 'POST':
        form = form_class(data=request.POST)

        if form.is_valid():
            company = request.POST.get(
                'company'
                , '')
            division = request.POST.get(
                'division'
                , '')
            name = request.POST.get(
                'name'
                , '')
            address = request.POST.get(
                'address'
                , '')
            phone_number = request.POST.get(
                'phone_number'
                , '')
            email = request.POST.get(
                'email'
                , '')
            content = request.POST.get('content', '')

            # Email the profile with the
            # contact information
            context = {
                'company'      : company,
                'division'     : division,
                'name'         : name,
                'address'      : address,
                'phone_number' : phone_number,
                'email'        : email,
                'content'      : content,
            }
            content = render_to_string('pages/contact_template.txt', context)

            email = EmailMessage(
                subject = "[ToMoCA] Thank you for contacting us",
                body = content,
                to = ["ks6088ts@gmail.com", "take@tomoca.jp", email],
            )
            email.send()
            return redirect('/')
        else:
            error_message = '入力データが不正です。再度入力をお願いします。/ Input data is invalid. Please fill in correct data.'
            return render(request, 'pages/contact.html', {
                'error': error_message,
                'form': form_class,
            })

    return render(request, 'pages/contact.html', {
        'form': form_class,
    })

products/views.py
from django.views import generic
from django.shortcuts import get_object_or_404

from .models import Product, Category


class ListView(generic.ListView):
    template_name = 'products/index.html'
    context_object_name = 'product_list'
    # paginate_by = 5
    ordering = '-pk'

    def get_queryset(self):
        return Product.objects.all()


index = ListView.as_view()


class DetailView(generic.DetailView):
    model = Product
    template_name = 'products/detail.html'

    def get_queryset(self):
        return Product.objects.all()


detail = DetailView.as_view()


class CategoryView(generic.ListView):
    template_name = 'products/index.html'
    context_object_name = 'product_list'
    # paginate_by = 5
    ordering = '-pk'

    def get_queryset(self):
        self.category = get_object_or_404(
            Category, category_text=self.kwargs["pk"])
        return Product.objects.filter(category=self.category)


category = CategoryView.as_view()

templates/pages/contact.html
{% extends 'products/base.html' %}

{% load static %}

{% block content %}

    <section>
        <div class="container">
            <div class="row">
                <div class="col-lg-9 text-left">
                  <h1>お問合せ / Contact</h1>
                  <p>
                    メールでのお問合せは以下のアドレスでも受け付けております。<br>
                    <img src="{% static 'tomoca/img/mail_address.png' %}" height="40px">
                  </p>
                  {% if error %}
                  <p>
                    <h1 style="color: #ff0000; background-color: transparent">{{error}}</h1>
                  </p>
                  {% endif %}
                  <form role="form" action="" method="post">
                      {% csrf_token %}
                      {{ form.as_p }}
                      <button type="submit" class="btn btn-primary">送信/Submit</button>
                  </form>
                  <div class="col-lg-3 text-left">
                  </div>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

templates/products/base.html
{% comment "Reference note" %}

* https://docs.djangoproject.com/en/1.11/ref/templates/language/

{% endcomment %}

{% load static %}


<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <link rel="icon" href="{% static 'tomoca/img/favicon.ico' %}">

    <title>Used digital measuring devices, ToMoCA Co., Ltd.</title>

    <!-- Bootstrap Core CSS -->
    <link href="{% static 'startbootstrap-sb-admin-2/vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- MetisMenu CSS -->
    <link href="{% static 'startbootstrap-sb-admin-2/vendor/metisMenu/metisMenu.min.css' %}" rel="stylesheet">

    <!-- DataTables CSS -->
    <link href="{% static 'startbootstrap-sb-admin-2/vendor/datatables-plugins/dataTables.bootstrap.css' %}" rel="stylesheet">

    <!-- DataTables Responsive CSS -->
    <link href="{% static 'startbootstrap-sb-admin-2/vendor/datatables-responsive/dataTables.responsive.css' %}" rel="stylesheet">

    <!-- Custom CSS -->
    <link href="{% static 'startbootstrap-sb-admin-2/dist/css/sb-admin-2.css' %}" rel="stylesheet">

    <!-- Custom Fonts -->
    <link href="{% static 'startbootstrap-sb-admin-2/vendor/font-awesome/css/font-awesome.min.css' %}" rel="stylesheet" type="text/css">

    <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- Global Site Tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=UA-91094240-4"></script>
    <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());

      gtag('config', 'UA-91094240-4');
    </script>

</head>

<body>

<div id="wrapper">

    <!-- Navigation -->
    <nav class="navbar navbar-default navbar-static-top" role="navigation" style="margin-bottom: 0">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="{% url 'pages:index' %}">
                <img alt="Corporate Logo" src="{% static 'tomoca/img/logo.png' %}" height="40px" style="padding-bottom: 10px;">
            </a>
        </div>
        <!-- /.navbar-header -->
    </nav>

    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                {% block content %}
                {% endblock %}
            </div>
            <!-- /.col-lg-12 -->
        </div>
    </div>
    <!-- /#page-wrapper -->

</div>
<!-- /#wrapper -->

<!-- jQuery -->
<script src="{% static 'startbootstrap-sb-admin-2/vendor/jquery/jquery.min.js' %}"></script>

<!-- Bootstrap Core JavaScript -->
<script src="{% static 'startbootstrap-sb-admin-2/vendor/bootstrap/js/bootstrap.min.js' %}"></script>

<!-- Metis Menu Plugin JavaScript -->
<script src="{% static 'startbootstrap-sb-admin-2/vendor/metisMenu/metisMenu.min.js' %}"></script>

<!-- DataTables JavaScript -->
<script src="{% static 'startbootstrap-sb-admin-2/vendor/datatables/js/jquery.dataTables.min.js' %}"></script>
<script src="{% static 'startbootstrap-sb-admin-2/vendor/datatables-plugins/dataTables.bootstrap.min.js' %}"></script>
<script src="{% static 'startbootstrap-sb-admin-2/vendor/datatables-responsive/dataTables.responsive.js' %}"></script>

<!-- Custom Theme JavaScript -->
<script src="{% static 'startbootstrap-sb-admin-2/dist/js/sb-admin-2.js' %}"></script>

<!-- Page-Level Demo Scripts - Tables - Use for reference -->
<script>
    $(document).ready(function() {
        $('#dataTables-example').DataTable({
            responsive: true
        });
    });
    </script>

</body>

</html>

templates/products/detail.html
{% extends 'products/base.html' %}

{% block content %}

{% load humanize %}

<h1>製品の詳細 / Product Detail</h1>

<div class="panel panel-default">

    <div class="panel-heading">
        Product Detail
    </div>

    <table width="100%" class="table table-striped table-bordered table-hover">
        <tbody>
        <tr>
            {% if product %}
            {% for image in product.image_set.all %}
            <td>
                <a href="{{ image.image.url }}" >
                    <img src={{ image.image.url }}  class="img-responsive" alt="Smiley face">
                </a>
            </td>
            {% endfor %}
            {% endif %}
        </tr>
        </tbody>
    </table>

    <!-- /.panel-heading -->
    <div class="panel-body">

        <table class="table">
            <tbody>
            <tr>
                <th scope="row" class="col-md-5">管理番号 / ID</th>
                <td  class="col-md-7"> {{ product.id | stringformat:"05d" }} </td>
            </tr>
            <tr>
                <th scope="row" class="col-md-5">型番 / Name</th>
                <td  class="col-md-7"> {{ product.product_text }} </td>
            </tr>
            <tr>
                <th scope="row" class="col-md-5">価格(税抜) / Price</th>
                <td  class="col-md-7">
                {% if product.inventory_status == "Sold" %}
                    ¥ --
                {% else %}
                    ¥ {{ product.price | intcomma}}
                {% endif %}
                </td>
            </tr>
            <tr>
                <th scope="row" class="col-md-5"> メーカー / Brand </th>
                <td  class="col-md-7"> {{ product.brand }} </td>
            </tr>
            <tr>
                <th scope="row" class="col-md-5"> カテゴリ / Category </th>
                <td  class="col-md-7"> {{ product.category }} </td>
            </tr>
            <tr>
                <th scope="row" class="col-md-5"> 仕様 / Specification </th>
                <td  class="col-md-7"> {{ product.measurable_range }} </td>
            </tr>
            <tr>
                <th scope="row" class="col-md-5"> オプション / Options </th>
                <td  class="col-md-7"> {{ product.option }} </td>
            </tr>
            <tr>
                <th scope="row" class="col-md-5"> 外観 / Rank </th>
                <td  class="col-md-7"> {{ product.rank }} </td>
            </tr>
            <tr>
                <th scope="row" class="col-md-5"> 製造年 / Year Of Manufacture </th>
                <td  class="col-md-7"> {{ product.year_of_manufacture |floatformat:"0" }} </td>
            </tr>
            <tr>
                <th scope="row" class="col-md-5"> 在庫状況 / Inventory Status </th>
                <td  class="col-md-7">
                {% if product.inventory_status == "Sold" %}
                    <div style="color:red;">
                {% else %}
                    <div>
                {% endif %}
                    {{ product.inventory_status }}
                    </div>
                </td>
            </tr>
            <tr>
                <th scope="row" class="col-md-5"> 詳細説明 / Description </th>
                <td  class="col-md-7">
                    <!-- https://torina.top/detail/256/ -->
                    {% autoescape off %}
                    {{ product.description }}
                    {% endautoescape %}
                </td>
            </tr>
            </tbody>
        </table>


        <a class="btn btn-primary" target="_blank" href="{% url 'pages:contact' %}">お問合せフォーム</a>

    </div>
    <!-- /.panel-body -->
</div>
<!-- /.panel -->


{% endblock %}

templates/products/index.html
{% extends 'products/base.html' %}

{% block content %}

{% load humanize %}

<h3>Category : {{ product_list.0.category }}</h3>

<div class="panel panel-default">

    <div class="panel-heading">
        Product List
    </div>
    <!-- /.panel-heading -->
    <div class="panel-body">

        <table width="100%" class="table table-striped table-bordered table-hover" id="dataTables-example">
            <thead>
            <tr>
                <th>Product Name</th>
                <th>ID</th>
                <th>Price</th>
                <th>Brand</th>
                <th>Specification</th>
                <th>Inventory Status</th>
            </tr>
            </thead>
            <tbody>
            {% if product_list %}
            {% for product in product_list %}

            {% if product.inventory_status == "Sold" %}
            <tr class="danger">
                <td><a href="{% url 'products:detail' product.id %}">{{ product.product_text }}</a></td>
                <td>{{ product.id | stringformat:"05d"}}</td>
                <td>--</td>
                <td>{{ product.brand }}</td>
                <td>{{ product.measurable_range }}</td>
                <td style="color:red;">{{ product.inventory_status }}</td>
            </tr>
            {% else %}
            <tr>
                <td><a href="{% url 'products:detail' product.id %}">{{ product.product_text }}</a></td>
                <td>{{ product.id | stringformat:"05d"}}</td>
                <td> ¥ {{ product.price | intcomma}}</td>
                <td>{{ product.brand }}</td>
                <td>{{ product.measurable_range }}</td>
                <td>{{ product.inventory_status }}</td>
            </tr>
            {% endif %}

            {% endfor %}
            {% else %}
            <tr>
                <td>Dummy</td>
                <td>Dummy</td>
                <td>Dummy</td>
                <td>Dummy</td>
                <td>Dummy</td>
                <td>Dummy</td>
                <td>Dummy</td>
                <td>Dummy</td>
            </tr>
            {% endif %}
            </tbody>
        </table>
        <!-- /.table-responsive -->

        <div class="well">
            <h4>欲しいものが見つかりませんか ?</h4>
            <p>
                製品探索サービスも請け負っております。
                下記リンクよりお問合せください。
            </p>
            <a class="btn btn-primary" target="_blank" href="{% url 'pages:contact' %}">お問合せフォーム</a>
        </div>
    </div>
    <!-- /.panel-body -->
</div>
<!-- /.panel -->

{% endblock %}